# Generated by Django 4.2.1 on 2024-03-25 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0004_rename_quizsubject_quizcategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="quiz_subject",
            new_name="quiz_category",
        ),
        migrations.RemoveField(
            model_name="question",
            name="number_of_questions",
        ),
        migrations.RemoveField(
            model_name="question",
            name="time",
        ),
        migrations.AddField(
            model_name="quizcategory",
            name="number_of_questions",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quizcategory",
            name="time",
            field=models.IntegerField(default=1, help_text="Duration in Seconds"),
        ),
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "quiz_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
